config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  root 'posts#index'

  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum:5 }
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:get_post]
  before_action :get_post, only: [:create, :destroy]

  def get_post
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :get_post, only: [:show, :edit, :update, :destroy]

  def get_post
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def show

  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<br />
<p class="comment_name">
  <strong><%= comment.name %></strong>
</p>
<p class="comment_body">
  <%= comment.body %>
</p>
<p class="comment_title">
  <%= time_ago_in_words(comment.created_at) %> Ago
</p>
<% if user_signed_in? %>
<p>
  | <%= link_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </p>
    <br />
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TumblrApp</title>
    <%= csrf_meta_tags %>

     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      #page {
        width: 680px;
        margin: 0 auto;
      }
      nav > ul {
        display: block;
        padding-left: 0;
      }
      nav > ul > li {
        display: inline;
      }
    </style>
  </head>

  <body>
  <div id="page">
    <nav>
      <ul>
        <li><%= link_to "Tumblr", root_path %></li>
        <li><%= link_to "Posts", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
        <% if user_signed_in? %>
          <li><%= link_to "New Post", new_post_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </nav>
    <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") %>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<%= image_tag "vinny.png" %>
<p>
  Chocolate cake marzipan brownie powder pudding pie gummies. Gingerbread lollipop tootsie roll. Donut danish sugar plum oat cake chupa chups macaroon dragée pastry oat cake. Jelly beans chupa chups topping lemon drops. Powder gingerbread pastry powder sweet roll candy canes apple pie cotton candy. Lollipop biscuit jujubes wafer pastry jujubes jelly beans sweet. Pie muffin sweet roll cheesecake pudding marzipan. Bear claw gummi bears caramels ice cream cookie sweet dessert macaroon. Lollipop muffin fruitcake marzipan soufflé apple pie tootsie roll fruitcake. Soufflé jelly-o bear claw biscuit. Cotton candy bear claw lemon drops candy canes muffin carrot cake. Cheesecake pudding soufflé. Tootsie roll jelly chocolate bar fruitcake pastry toffee pastry sweet roll. Lemon drops cake tart brownie.
</p>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div id="errors">
          <h2>
            <%= pluralize(@post.errors.count, "error") %> stopped this post from saving
          </h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit this post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Tumblr Root</h1>
<% @posts.each do |post| %>
<h3><%= link_to post.title, post %></h3>
<p>
  <%= time_ago_in_words(post.created_at) %> ago
</p>
<p>
  <%= truncate(post.body, length:200) %>
</p>
<br />
<% end %>

app/views/posts/new.html.erb
<h1>Make a Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>Submitted <%= time_ago_in_words(@post.created_at) %> ago
  <% if user_signed_in? %>
  | <%= link_to 'Edit', edit_post_path %>
  | <%= link_to 'Delete', post_path, method: :delete %></p>
  <% end %>
<br />
<p><%= @post.body %></p>
<div id="comments">
  <h2><%= @post.comments.count %> Comments</h2>
  <%= render @post.comments %>
  <br />
  <h3>Join Discussion: </h3>
  <%= render 'comments/form' %>
</div>